import type { Finding, Decision } from '../core/types.js';

export interface GerritChangeState {
  provider: 'gerrit';
  changeNumber: string;
  revision: string;
  project: string;
  branch: string;
  subject: string;
  labels: Record<string, number>;
  source: 'provider-api';
}

export interface GerritReviewResult { changeNumber: string; revision: string; labels: Record<string, number>; published: true; }

type Auth = { mode: 'bearer'; token: string } | { mode: 'basic'; username: string; password: string };

function decode(body: string): unknown {
  const text = body.replace(/^\)\]\}'\s*\n?/, '');
  return text.trim() ? JSON.parse(text) : {};
}
function num(value: unknown): number | null { return typeof value === 'number' && Number.isFinite(value) ? value : null; }
function labelVote(value: unknown): number {
  if (!value || typeof value !== 'object') return 0;
  const o=value as Record<string,unknown>;
  const approved=num(o.value); if(approved!==null) return approved;
  const all=Array.isArray(o.all)?o.all:[];
  let best=0; for(const item of all){ if(item&&typeof item==='object'){ const v=num((item as Record<string,unknown>).value); if(v!==null && Math.abs(v)>Math.abs(best)) best=v; } }
  return best;
}
function authHeader(auth: Auth): string { return auth.mode==='bearer' ? `Bearer ${auth.token}` : `Basic ${Buffer.from(`${auth.username}:${auth.password}`).toString('base64')}`; }

export class GerritProvider {
  constructor(private readonly options:{ apiBaseUrl:string; auth:Auth; timeoutMs?:number }){}
  private async request(method:string,path:string,body?:unknown):Promise<unknown>{
    const controller=new AbortController(); const timer=setTimeout(()=>controller.abort(),this.options.timeoutMs??15000);
    try{
      const response=await fetch(`${this.options.apiBaseUrl.replace(/\/$/,'')}/a${path}`,{method,headers:{accept:'application/json','content-type':'application/json',authorization:authHeader(this.options.auth),'user-agent':'quilons-sentrycode'},...(body===undefined?{}:{body:JSON.stringify(body)}),signal:controller.signal});
      const text=await response.text();
      if(!response.ok) throw new Error(`Gerrit ${method} ${path} failed: HTTP ${response.status}${text.trim()?` ${text.slice(0,200)}`:''}`);
      return decode(text);
    } finally { clearTimeout(timer); }
  }
  async health():Promise<string>{ const body=await this.request('GET','/config/server/version'); return typeof body==='string'?body:String(body); }
  async inspect(changeNumber:string,revision='current'):Promise<GerritChangeState>{
    const body=await this.request('GET',`/changes/${encodeURIComponent(changeNumber)}/detail?o=DETAILED_LABELS&o=CURRENT_REVISION`);
    const o=(body&&typeof body==='object'?body:{}) as Record<string,unknown>;
    const labelsRaw=(o.labels&&typeof o.labels==='object'?o.labels:{}) as Record<string,unknown>;
    const labels:Record<string,number>={}; for(const [key,value] of Object.entries(labelsRaw)) labels[key]=labelVote(value);
    return {provider:'gerrit',changeNumber:String(o._number??changeNumber),revision:String(o.current_revision??revision),project:String(o.project??''),branch:String(o.branch??''),subject:String(o.subject??''),labels,source:'provider-api'};
  }
  async publishReview(input:{changeNumber:string;revision:string;message:string;findings:Finding[];label?:string;vote?:number;notify?:'NONE'|'OWNER'|'OWNER_REVIEWERS'|'ALL'}):Promise<GerritReviewResult>{
    const comments:Record<string,Array<{line?:number;message:string;unresolved:boolean}>>={};
    for(const finding of input.findings){ if(!finding.location?.path) continue; (comments[finding.location.path]??=[]).push({...(finding.location.line?{line:finding.location.line}:{}),message:`[SentryCode/${finding.severity}] ${finding.ruleId}: ${finding.title}\n${finding.description}`,unresolved:['high','critical'].includes(finding.severity)}); }
    const labels=input.label&&input.vote!==undefined?{[input.label]:input.vote}:{};
    await this.request('POST',`/changes/${encodeURIComponent(input.changeNumber)}/revisions/${encodeURIComponent(input.revision)}/review`,{message:input.message,labels,comments,notify:input.notify??'OWNER_REVIEWERS',tag:'autogenerated:quilons-sentrycode'});
    return {changeNumber:input.changeNumber,revision:input.revision,labels,published:true};
  }
}

export function gerritAuthFromEnv(config:{authMode:'bearer'|'basic';tokenEnv:string;usernameEnv:string;passwordEnv:string},env:Record<string,string|undefined>=process.env):Auth{
  if(config.authMode==='bearer'){ const token=env[config.tokenEnv]??''; if(!token) throw new Error(`Gerrit is enabled but ${config.tokenEnv} is not set`); return {mode:'bearer',token}; }
  const username=env[config.usernameEnv]??''; const password=env[config.passwordEnv]??'';
  if(!username||!password) throw new Error(`Gerrit is enabled but ${config.usernameEnv} and ${config.passwordEnv} are required`);
  return {mode:'basic',username,password};
}

export function gerritReviewMessage(decision:Decision,findings:Finding[]):string{
  const active=findings.filter(f=>['medium','high','critical'].includes(f.severity));
  const counts=active.reduce<Record<string,number>>((a,f)=>{a[f.severity]=(a[f.severity]??0)+1;return a;},{});
  return `QUILONS SentryCode: ${decision}\nFindings: ${findings.length}; critical=${counts.critical??0}, high=${counts.high??0}, medium=${counts.medium??0}.\nSee SentryCode evidence for the authoritative report.`;
}
