import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import type { ComplianceIdentity } from '../compliance/contracts.js';
import type { SentryCodeConfig } from '../core/types.js';
import { stableId } from '../utils/hash.js';
import { appendAuditEvent } from '../enterprise/audit.js';
import type { ApplicationStateStore } from './store.js';
import type { AdminRole, IntegrationRecord, ManagedPolicyAssignment, ManagedScannerSetting, PrincipalRecord, RegisteredRepository, WaiverWorkflowRecord } from './types.js';

const allowedScanners = new Set(['secrets','dependencies','sast','git-assurance','provenance','automotive']);
const severities = new Set(['info','low','medium','high','critical']);
export class SentryCodeAdminService {
  private async governedAudit(type:string, detail:Record<string,string|number|boolean|null>, actor:string){ await appendAuditEvent(this.root,this.config.integrity.auditLogFile,type,detail,actor,this.config.integrity.evidenceSigningPrivateKeyFile||undefined); }
  constructor(private readonly root:string, private readonly config:SentryCodeConfig, private readonly identity:ComplianceIdentity|null, private readonly store:ApplicationStateStore) {}
  private scope(){ if(!this.identity) throw new Error('UI_SCOPE_NOT_CONFIGURED'); return this.identity; }
  private async requireRepository(id:string){ const repo=(await this.repositories()).find(x=>x.id===id); if(!repo) throw new Error('REPOSITORY_SCOPE_MISMATCH'); return repo; }
  async state(){ const scope=this.identity; const db=await this.store.status(); return { database:db, scope, writable:Boolean(scope && db.connected) && !this.config.integrity.requireSignedConfig }; }
  async repositories(){ const s=this.scope(); return this.store.listRepositories(s.tenant,s.project); }
  async registerRepository(input:any, actor:string){ const s=this.scope(); const name=String(input.name??'').trim(); const rootPath=String(input.rootPath??'').trim(); if(!name||!rootPath) throw new Error('repository name and rootPath are required'); const id=stableId('repo',`${s.tenant}|${s.project}|${name}`); const v=await this.store.upsertRepository({id,tenant:s.tenant,project:s.project,name,rootPath,defaultBranch:String(input.defaultBranch??'main'),enabled:input.enabled!==false},actor); await this.governedAudit('ui.repository.upsert',{repositoryId:v.id,tenant:v.tenant,project:v.project},actor); return v; }
  async scanners(repositoryId:string){ await this.requireRepository(repositoryId); return this.store.listScannerSettings(repositoryId); }
  async setScanner(repositoryId:string,input:any,actor:string){ await this.requireRepository(repositoryId); const scanner=String(input.scanner??''); if(!allowedScanners.has(scanner)) throw new Error('unsupported scanner'); const failureMode=String(input.failureMode??'fail') as ManagedScannerSetting['failureMode']; if(!['fail','warn','ignore'].includes(failureMode)) throw new Error('invalid failureMode'); const value=await this.store.upsertScannerSetting({repositoryId,scanner,enabled:Boolean(input.enabled),required:Boolean(input.required),failureMode},actor); await this.governedAudit('ui.scanner.update',{repositoryId,scanner,enabled:value.enabled,required:value.required,failureMode:value.failureMode},actor); return value; }
  async policies(){ const s=this.scope(); return this.store.listPolicies(s.tenant,s.project); }
  async setPolicy(input:any,actor:string){ const s=this.scope(); const failOn=Array.isArray(input.failOn)?input.failOn.map(String):[]; const warnOn=Array.isArray(input.warnOn)?input.warnOn.map(String):[]; if([...failOn,...warnOn].some((x)=>!severities.has(x))) throw new Error('invalid severity in policy'); if(input.repositoryId) await this.requireRepository(String(input.repositoryId)); const id=stableId('managed-policy',`${s.tenant}|${s.project}|${input.repositoryId??'*'}|${input.service??'*'}`); const value=await this.store.upsertPolicy({id,tenant:s.tenant,project:s.project,repositoryId:input.repositoryId?String(input.repositoryId):null,service:input.service?String(input.service):null,failOn,warnOn,requiredScanners:Array.isArray(input.requiredScanners)?input.requiredScanners.map(String):[],scannerFailureModes:(input.scannerFailureModes&&typeof input.scannerFailureModes==='object')?input.scannerFailureModes:{},lockedFields:Array.isArray(input.lockedFields)?input.lockedFields.map(String):[]},actor); await this.governedAudit('ui.policy.upsert',{policyId:value.id,tenant:value.tenant,project:value.project,version:value.version},actor); return value; }
  async waivers(){ const s=this.scope(); return this.store.listWaivers(s.tenant,s.project); }
  async requestWaiver(input:any,actor:string){ const s=this.scope(); const reason=String(input.reason??'').trim(); const expiresAt=String(input.expiresAt??''); if(!reason || Number.isNaN(new Date(expiresAt).getTime())) throw new Error('reason and valid expiresAt are required'); if(!input.fingerprint&&!input.ruleId&&!input.path&&!input.scanner) throw new Error('waiver requires finding scope'); const now=new Date().toISOString(); const status=this.config.waivers.requireApproval?'pending':'active'; if(input.repositoryId) await this.requireRepository(String(input.repositoryId)); const value:WaiverWorkflowRecord={id:stableId('waiver',`${s.tenant}|${s.project}|${actor}|${reason}|${now}`),tenant:s.tenant,project:s.project,repositoryId:input.repositoryId?String(input.repositoryId):null,findingId:input.findingId?String(input.findingId):null,ruleId:input.ruleId?String(input.ruleId):null,scanner:input.scanner?String(input.scanner):null,path:input.path?String(input.path):null,fingerprint:input.fingerprint?String(input.fingerprint):null,reason,ticket:input.ticket?String(input.ticket):null,author:actor,approver:status==='active'?actor:null,status,createdAt:now,expiresAt,decidedAt:status==='active'?now:null}; if(this.config.waivers.requireTicket&&!value.ticket) throw new Error('ticket required by waiver policy'); const created=await this.store.createWaiver(value); await this.governedAudit('ui.waiver.request',{waiverId:created.id,status:created.status},actor); return created; }
  async decideWaiver(id:string,status:'active'|'rejected'|'revoked',actor:string){ const scoped=(await this.waivers()).find(x=>x.id===id); if(!scoped) return null; const v=await this.store.transitionWaiver(id,status,actor); if(v) await this.governedAudit(`ui.waiver.${status}`,{waiverId:id,status},actor); return v; }
  async integrations(){ const s=this.scope(); return this.store.listIntegrations(s.tenant,s.project); }
  async setIntegration(input:any,actor:string){ const s=this.scope(); const kind=String(input.kind??'').trim(); const name=String(input.name??kind).trim(); if(!kind||!name) throw new Error('integration kind and name are required'); const value:Omit<IntegrationRecord,'updatedAt'|'updatedBy'>={id:stableId('integration',`${s.tenant}|${s.project}|${kind}|${name}`),tenant:s.tenant,project:s.project,kind,name,enabled:input.enabled!==false,configuration:(input.configuration&&typeof input.configuration==='object')?input.configuration:{},secretReference:input.secretReference?String(input.secretReference):null,status:input.status??'configured'}; const saved=await this.store.upsertIntegration(value,actor); await this.governedAudit('ui.integration.upsert',{integrationId:saved.id,kind:saved.kind,enabled:saved.enabled},actor); return saved; }
  async audit(){ return this.store.listAudit(); }
  async principals(){ return this.store.listPrincipals(); }
  async setPrincipal(input:any,actor:string){
    const subject=String(input.subject??'').trim(); const displayName=String(input.displayName??subject).trim();
    const role=String(input.role??'viewer') as AdminRole;
    if(!subject||!displayName) throw new Error('principal subject and displayName are required');
    if(!['viewer','engineer','security_admin','administrator'].includes(role)) throw new Error('invalid principal role');
    const existing=(await this.store.listPrincipals()).find(x=>x.subject===subject);
    const now=new Date().toISOString();
    const value:PrincipalRecord={id:existing?.id??stableId('principal',subject),subject,displayName,role,enabled:input.enabled!==false,createdAt:existing?.createdAt??now,updatedAt:now};
    const saved=await this.store.upsertPrincipal(value);
    await this.governedAudit('ui.principal.upsert',{principalId:saved.id,role:saved.role,enabled:saved.enabled},actor);
    return saved;
  }
  async materializePolicy(repository:RegisteredRepository, policy:ManagedPolicyAssignment){ if(this.config.integrity.requireSignedConfig) throw new Error('SIGNED_CONFIG_WRITE_BLOCKED'); const safe=policy.id.replace(/[^A-Za-z0-9._-]/g,'_'); const path=resolve(repository.rootPath,`.sentrycode/policies/80-ui-managed-${safe}.json`); await mkdir(dirname(path),{recursive:true}); const level=policy.service?'service':policy.repositoryId?'repository':'project'; const scope:any={tenant:policy.tenant,project:policy.project,repository:repository.name}; if(policy.service)scope.service=policy.service; const doc={schemaVersion:1,id:policy.id,version:String(policy.version),level,scope,description:'Managed by SentryCode Web UI',enforcement:{failOn:policy.failOn,warnOn:policy.warnOn,requiredScanners:policy.requiredScanners,scannerFailureModes:policy.scannerFailureModes},lock:policy.lockedFields}; await writeFile(path,`${JSON.stringify(doc,null,2)}\n`,'utf8'); return path; }
  async materializeWaivers(repository:RegisteredRepository, all:WaiverWorkflowRecord[]){ if(this.config.integrity.requireSignedConfig) throw new Error('SIGNED_CONFIG_WRITE_BLOCKED'); const path=resolve(repository.rootPath,this.config.waivers.file); let existing:any[]=[]; try{const v=JSON.parse(await readFile(path,'utf8')); if(Array.isArray(v))existing=v;}catch{} const managedIds=new Set(all.map(x=>x.id)); const preserved=existing.filter(x=>!x||typeof x!=='object'||!managedIds.has(String(x.id??''))); const active=all.filter(x=>x.status==='active').map(x=>({id:x.id,reason:x.reason,expiresAt:x.expiresAt,...(x.fingerprint?{fingerprint:x.fingerprint}:{}),...(x.ruleId?{ruleId:x.ruleId}:{}),...(x.path?{path:x.path}:{}),...(x.scanner?{scanner:x.scanner}:{}),repository:repository.name,...(x.ticket?{ticket:x.ticket}:{}),createdAt:x.createdAt,author:x.author,...(x.approver?{approver:x.approver,approvedAt:x.decidedAt}: {})})); await mkdir(dirname(path),{recursive:true}); await writeFile(path,`${JSON.stringify([...preserved,...active],null,2)}\n`,'utf8'); return path; }
  async materializeScannerConfig(repository:RegisteredRepository, settings:ManagedScannerSetting[]){ if(this.config.integrity.requireSignedConfig) throw new Error('SIGNED_CONFIG_WRITE_BLOCKED'); const path=resolve(repository.rootPath,'.sentrycode/config.json'); let raw:any={schemaVersion:1}; try{raw=JSON.parse(await readFile(path,'utf8'));}catch{}; for(const s of settings){ if(s.scanner==='secrets') raw.secrets={...(raw.secrets??{}),enabled:s.enabled}; if(s.scanner==='dependencies') raw.dependencies={...(raw.dependencies??{}),enabled:s.enabled}; if(s.scanner==='sast') raw.sast={...(raw.sast??{}),enabled:s.enabled}; if(s.scanner==='git-assurance') raw.gitAssurance={...(raw.gitAssurance??{}),enabled:s.enabled}; if(s.scanner==='provenance') raw.provenance={...(raw.provenance??{}),enabled:s.enabled}; if(s.scanner==='automotive') raw.automotive={...(raw.automotive??{}),enabled:s.enabled}; }
    raw.policy={...(raw.policy??{}),requiredScanners:settings.filter(x=>x.required).map(x=>x.scanner),scannerFailureModes:Object.fromEntries(settings.map(x=>[x.scanner,x.failureMode]))}; await mkdir(dirname(path),{recursive:true}); await writeFile(path,`${JSON.stringify(raw,null,2)}\n`,'utf8'); return path; }
}
