import { readFile } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { Pool, PoolClient } from 'pg';
import type { ApplicationStateStore } from './store.js';
import type { ApplicationAuditRecord, ApplicationStateStatus, IntegrationRecord, ManagedPolicyAssignment, ManagedScannerSetting, PrincipalRecord, RegisteredRepository, WaiverWorkflowRecord } from './types.js';

function rowRepo(row: any): RegisteredRepository { return { id: row.id, tenant: row.tenant, project: row.project, name: row.name, rootPath: row.root_path, defaultBranch: row.default_branch, enabled: row.enabled, createdAt: new Date(row.created_at).toISOString(), updatedAt: new Date(row.updated_at).toISOString() }; }
function rowScanner(row: any): ManagedScannerSetting { return { repositoryId: row.repository_id, scanner: row.scanner, enabled: row.enabled, required: row.required, failureMode: row.failure_mode, updatedAt: new Date(row.updated_at).toISOString(), updatedBy: row.updated_by }; }
function rowPolicy(row: any): ManagedPolicyAssignment { return { id: row.id, tenant: row.tenant, project: row.project, repositoryId: row.repository_id, service: row.service, failOn: row.fail_on ?? [], warnOn: row.warn_on ?? [], requiredScanners: row.required_scanners ?? [], scannerFailureModes: row.scanner_failure_modes ?? {}, lockedFields: row.locked_fields ?? [], version: row.version, updatedAt: new Date(row.updated_at).toISOString(), updatedBy: row.updated_by }; }
function rowWaiver(row: any): WaiverWorkflowRecord { return { id: row.id, tenant: row.tenant, project: row.project, repositoryId: row.repository_id, findingId: row.finding_id, ruleId: row.rule_id, scanner: row.scanner, path: row.path, fingerprint: row.fingerprint, reason: row.reason, ticket: row.ticket, author: row.author, approver: row.approver, status: row.status, createdAt: new Date(row.created_at).toISOString(), expiresAt: new Date(row.expires_at).toISOString(), decidedAt: row.decided_at ? new Date(row.decided_at).toISOString() : null }; }
function rowIntegration(row: any): IntegrationRecord { return { id: row.id, tenant: row.tenant, project: row.project, kind: row.kind, name: row.name, enabled: row.enabled, configuration: row.configuration ?? {}, secretReference: row.secret_reference, status: row.status, updatedAt: new Date(row.updated_at).toISOString(), updatedBy: row.updated_by }; }
function rowPrincipal(row: any): PrincipalRecord { return { id: row.id, subject: row.subject, displayName: row.display_name, role: row.role, enabled: row.enabled, createdAt: new Date(row.created_at).toISOString(), updatedAt: new Date(row.updated_at).toISOString() }; }
function rowAudit(row: any): ApplicationAuditRecord { return { id: row.id, at: new Date(row.at).toISOString(), actor: row.actor, action: row.action, entityType: row.entity_type, entityId: row.entity_id, detail: row.detail ?? {} }; }

export class PostgresApplicationStateStore implements ApplicationStateStore {
  constructor(private readonly pool: Pool) {}
  async status(): Promise<ApplicationStateStatus> {
    try {
      const result = await this.pool.query<{ version: number }>('SELECT max(version)::int AS version FROM sentrycode_schema_migrations');
      return { configured: true, connected: true, schemaVersion: result.rows[0]?.version ?? null, detail: 'PostgreSQL application state connected' };
    } catch (error) { return { configured: true, connected: false, schemaVersion: null, detail: (error as Error).message }; }
  }
  async migrate(): Promise<number> {
    const here = dirname(fileURLToPath(import.meta.url));
    const candidates = [resolve(here, '../../migrations/001_application_state.sql'), resolve(process.cwd(), 'migrations/001_application_state.sql')];
    let sql = '';
    for (const candidate of candidates) { try { sql = await readFile(candidate, 'utf8'); break; } catch {} }
    if (!sql) throw new Error('SentryCode migration 001_application_state.sql not found');
    await this.pool.query(sql); return 1;
  }
  async listRepositories(tenant: string, project: string) { const r=await this.pool.query('SELECT * FROM sentrycode_repositories WHERE tenant=$1 AND project=$2 ORDER BY name',[tenant,project]); return r.rows.map(rowRepo); }
  async upsertRepository(v: Omit<RegisteredRepository,'createdAt'|'updatedAt'>, actor: string) { const r=await this.pool.query(`INSERT INTO sentrycode_repositories(id,tenant,project,name,root_path,default_branch,enabled) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(id) DO UPDATE SET name=excluded.name,root_path=excluded.root_path,default_branch=excluded.default_branch,enabled=excluded.enabled,updated_at=now() RETURNING *`,[v.id,v.tenant,v.project,v.name,v.rootPath,v.defaultBranch,v.enabled]); await this.audit(actor,'repository.upsert','repository',v.id,{tenant:v.tenant,project:v.project}); return rowRepo(r.rows[0]); }
  async listScannerSettings(repositoryId: string){ const r=await this.pool.query('SELECT * FROM sentrycode_scanner_settings WHERE repository_id=$1 ORDER BY scanner',[repositoryId]); return r.rows.map(rowScanner); }
  async upsertScannerSetting(v: Omit<ManagedScannerSetting,'updatedAt'|'updatedBy'>, actor:string){ const r=await this.pool.query(`INSERT INTO sentrycode_scanner_settings(repository_id,scanner,enabled,required,failure_mode,updated_by) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(repository_id,scanner) DO UPDATE SET enabled=excluded.enabled,required=excluded.required,failure_mode=excluded.failure_mode,updated_at=now(),updated_by=excluded.updated_by RETURNING *`,[v.repositoryId,v.scanner,v.enabled,v.required,v.failureMode,actor]); await this.audit(actor,'scanner.update','scanner',`${v.repositoryId}:${v.scanner}`,{enabled:v.enabled,required:v.required,failureMode:v.failureMode}); return rowScanner(r.rows[0]); }
  async listPolicies(tenant:string,project:string){ const r=await this.pool.query('SELECT * FROM sentrycode_policy_assignments WHERE tenant=$1 AND project=$2 ORDER BY repository_id NULLS FIRST, service NULLS FIRST',[tenant,project]); return r.rows.map(rowPolicy); }
  async upsertPolicy(v: Omit<ManagedPolicyAssignment,'version'|'updatedAt'|'updatedBy'>, actor:string){ const r=await this.pool.query(`INSERT INTO sentrycode_policy_assignments(id,tenant,project,repository_id,service,fail_on,warn_on,required_scanners,scanner_failure_modes,locked_fields,updated_by) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7::jsonb,$8::jsonb,$9::jsonb,$10::jsonb,$11) ON CONFLICT(id) DO UPDATE SET fail_on=excluded.fail_on,warn_on=excluded.warn_on,required_scanners=excluded.required_scanners,scanner_failure_modes=excluded.scanner_failure_modes,locked_fields=excluded.locked_fields,version=sentrycode_policy_assignments.version+1,updated_at=now(),updated_by=excluded.updated_by RETURNING *`,[v.id,v.tenant,v.project,v.repositoryId,v.service,JSON.stringify(v.failOn),JSON.stringify(v.warnOn),JSON.stringify(v.requiredScanners),JSON.stringify(v.scannerFailureModes),JSON.stringify(v.lockedFields),actor]); await this.audit(actor,'policy.upsert','policy',v.id,{repositoryId:v.repositoryId,service:v.service}); return rowPolicy(r.rows[0]); }
  async listWaivers(tenant:string,project:string){ const r=await this.pool.query(`UPDATE sentrycode_waiver_workflow SET status='expired' WHERE tenant=$1 AND project=$2 AND status IN ('active','pending') AND expires_at<=now() RETURNING id`,[tenant,project]); void r; const q=await this.pool.query('SELECT * FROM sentrycode_waiver_workflow WHERE tenant=$1 AND project=$2 ORDER BY created_at DESC',[tenant,project]); return q.rows.map(rowWaiver); }
  async createWaiver(v:WaiverWorkflowRecord){ const r=await this.pool.query(`INSERT INTO sentrycode_waiver_workflow(id,tenant,project,repository_id,finding_id,rule_id,scanner,path,fingerprint,reason,ticket,author,approver,status,created_at,expires_at,decided_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17) RETURNING *`,[v.id,v.tenant,v.project,v.repositoryId,v.findingId,v.ruleId,v.scanner,v.path,v.fingerprint,v.reason,v.ticket,v.author,v.approver,v.status,v.createdAt,v.expiresAt,v.decidedAt]); await this.audit(v.author,'waiver.request','waiver',v.id,{status:v.status,reason:v.reason}); return rowWaiver(r.rows[0]); }
  async transitionWaiver(id:string,status:'active'|'rejected'|'revoked',actor:string){ const r=await this.pool.query(`UPDATE sentrycode_waiver_workflow SET status=$2,approver=CASE WHEN $2='active' THEN $3 ELSE approver END,decided_at=now() WHERE id=$1 RETURNING *`,[id,status,actor]); if(!r.rows[0]) return null; await this.audit(actor,`waiver.${status}`,'waiver',id,{status}); return rowWaiver(r.rows[0]); }
  async listIntegrations(tenant:string,project:string){ const r=await this.pool.query('SELECT * FROM sentrycode_integrations WHERE tenant=$1 AND project=$2 ORDER BY kind,name',[tenant,project]); return r.rows.map(rowIntegration); }
  async upsertIntegration(v:Omit<IntegrationRecord,'updatedAt'|'updatedBy'>,actor:string){ const r=await this.pool.query(`INSERT INTO sentrycode_integrations(id,tenant,project,kind,name,enabled,configuration,secret_reference,status,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb,$8,$9,$10) ON CONFLICT(id) DO UPDATE SET name=excluded.name,enabled=excluded.enabled,configuration=excluded.configuration,secret_reference=excluded.secret_reference,status=excluded.status,updated_at=now(),updated_by=excluded.updated_by RETURNING *`,[v.id,v.tenant,v.project,v.kind,v.name,v.enabled,JSON.stringify(v.configuration),v.secretReference,v.status,actor]); await this.audit(actor,'integration.upsert','integration',v.id,{kind:v.kind,enabled:v.enabled}); return rowIntegration(r.rows[0]); }
  async listPrincipals(){ const r=await this.pool.query('SELECT * FROM sentrycode_principals ORDER BY display_name'); return r.rows.map(rowPrincipal); }
  async upsertPrincipal(v:PrincipalRecord){ const r=await this.pool.query(`INSERT INTO sentrycode_principals(id,subject,display_name,role,enabled,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(id) DO UPDATE SET subject=excluded.subject,display_name=excluded.display_name,role=excluded.role,enabled=excluded.enabled,updated_at=now() RETURNING *`,[v.id,v.subject,v.displayName,v.role,v.enabled,v.createdAt,v.updatedAt]); await this.audit(v.subject,'principal.upsert','principal',v.id,{role:v.role,enabled:v.enabled}); return rowPrincipal(r.rows[0]); }
  async appendAudit(v:ApplicationAuditRecord){ await this.pool.query(`INSERT INTO sentrycode_application_audit(id,at,actor,action,entity_type,entity_id,detail) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb)`,[v.id,v.at,v.actor,v.action,v.entityType,v.entityId,JSON.stringify(v.detail)]); }
  async listAudit(limit=200){ const r=await this.pool.query('SELECT * FROM sentrycode_application_audit ORDER BY at DESC LIMIT $1',[limit]); return r.rows.map(rowAudit); }
  async close(){ await this.pool.end(); }
  private async audit(actor:string,action:string,entityType:string,entityId:string,detail:Record<string,unknown>){ const at=new Date().toISOString(); const id=`${action}:${entityId}:${Date.now()}:${Math.random().toString(16).slice(2)}`; await this.appendAudit({id,at,actor,action,entityType,entityId,detail}); }
}

export async function createPostgresApplicationStateStore(connectionString: string): Promise<PostgresApplicationStateStore> {
  const pg = await import('pg');
  const pool = new pg.Pool({ connectionString, max: 10, connectionTimeoutMillis: 5_000, idleTimeoutMillis: 30_000, application_name: 'quilons-sentrycode' });
  return new PostgresApplicationStateStore(pool);
}
